include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    prefer_asserts_with_message: ignore
    document_ignores: ignore
  exclude:
    - build/**
    - sample_app/build/**
    - package/build/**

formatter:
  page_width: 100

linter:
  rules:
    file_names: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
