// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOiTv-8jekkeCow2u-Xiz9TKbSvVrh-I',
    appId: '1:14684720471:android:ec499de8852c539a198212',
    messagingSenderId: '14684720471',
    projectId: 'wnmc-8949',
    storageBucket: 'wnmc-8949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF4Azn5G-CM6jncXWpUbfkUVnOcgr_LCM',
    appId: '1:14684720471:ios:65782209b671eab2198212',
    messagingSenderId: '14684720471',
    projectId: 'wnmc-8949',
    storageBucket: 'wnmc-8949.appspot.com',
    androidClientId: '14684720471-hir7kpkv0bt6o4uqsb73cv1fou6lvmsg.apps.googleusercontent.com',
    iosClientId: '14684720471-48ksui02porave87lp9qu01pvdr4k2g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.template1',
  );
}
