// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3br4JCNCC64c-2JIjTwxGiT6DfS62Ob4',
    appId: '1:351431708551:web:1751387ab4b6e37482cd22',
    messagingSenderId: '351431708551',
    projectId: 'torreyana-1',
    authDomain: 'torreyana-1.firebaseapp.com',
    storageBucket: 'torreyana-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTaZsjb9pTX_vqjQcd-JFbDj12Q7P-FOo',
    appId: '1:351431708551:android:5ea7f586b866c49b82cd22',
    messagingSenderId: '351431708551',
    projectId: 'torreyana-1',
    storageBucket: 'torreyana-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_tMeT9ttgZZoGPtnEz_faNon1awkogs',
    appId: '1:351431708551:ios:303fed129a50993e82cd22',
    messagingSenderId: '351431708551',
    projectId: 'torreyana-1',
    storageBucket: 'torreyana-1.firebasestorage.app',
    iosClientId: '351431708551-7kkva3kmcodqd95glinsdgiul6229rgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH_tMeT9ttgZZoGPtnEz_faNon1awkogs',
    appId: '1:351431708551:ios:303fed129a50993e82cd22',
    messagingSenderId: '351431708551',
    projectId: 'torreyana-1',
    storageBucket: 'torreyana-1.firebasestorage.app',
    iosClientId: '351431708551-7kkva3kmcodqd95glinsdgiul6229rgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3br4JCNCC64c-2JIjTwxGiT6DfS62Ob4',
    appId: '1:351431708551:web:a0c3ac1c5954dae582cd22',
    messagingSenderId: '351431708551',
    projectId: 'torreyana-1',
    authDomain: 'torreyana-1.firebaseapp.com',
    storageBucket: 'torreyana-1.firebasestorage.app',
  );
}